name: Descomprimir Portfolio

on:
  push:
    branches:
      - main  # Si tu rama se llama "master", cámbialo aquí

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Eliminar archivos antiguos
        run: |
          # Borra todo excepto .git y .github
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +

      - name: Descomprimir Portfolio.zip
        run: |
          unzip Portfolio.zip -d ./ 
          rm Portfolio.zip  # Elimina el ZIP después de descomprimir

      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Descomprimir Portfolio.zip"
          git push
